export const TitleOptions = [
  { label: "Mr", value: "mr" },
  { label: "Mrs", value: "mrs" },
  { label: "Ms", value: "ms" },
  { label: "Miss", value: "miss" },
];

export const MaritalStatusOptions = [
  { label: "Single", value: "single" },
  { label: "Married", value: "married" },
  { label: "Divorced", value: "divorced" },
  { label: "Widowed", value: "widowed" },
  { label: "Separated", value: "separated" },
  { label: "Civil-Partnered", value: "civil-partnered" },
] as const;

export const GenderOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
  { label: "Other", value: "other" },
  { label: "Prefer not to say", value: "prefer-not-to-say" },
] as const;

export const ImmigrationStatusOptions = [
  { label: "British Citizen", value: "british-citizen" },
  { label: "Refugee (granted asylum in the UK)", value: "refugee" },
  {
    label: "Asylum Seeker (awaiting a decision on your asylum application)",
    value: "asylum-seeker",
  },
  {
    label: "Leave to Remain (e.g., Limited Leave, Indefinite Leave to Remain)",
    value: "leave-to-remain",
  },
  {
    label: "EU/EEA Citizen with Pre-Settled or Settled Status",
    value: "eu-eea-settled",
  },
  { label: "Other", value: "other" },
] as const;

export const TenancyTypeOptions = [
  { label: "Private tenant", value: "private-tenant" },
  { label: "Council tenant", value: "council-tenant" },
  { label: "Housing Association tenant", value: "housing-association-tenant" },
  { label: "Living with parents", value: "living-with-parents" },
  { label: "Homeowner", value: "homeowner" },
  { label: "Lodger", value: "lodger" },
  { label: "Other", value: "other" },
  { label: "Assured Shorthold", value: "assured-shorthold" },
  { label: "Assured", value: "assured" },
  { label: "Regulated", value: "regulated" },
  { label: "License Agreement", value: "license-agreement" },
] as const;

export const SituationOptions = [
  { label: "Eviction", value: "eviction" },
  { label: "Domestic Abuse", value: "domestic-abuse" },
  { label: "Family Breakdown", value: "family-breakdown" },
  { label: "Mental Health Issues", value: "mental-health-issues" },
  { label: "Substance Misuse", value: "substance-misuse" },
  { label: "Release from prison", value: "release-from-prison" },
  { label: "Financial Difficulties", value: "financial-difficulties" },
  { label: "Housing Condition Issues", value: "housing-condition-issues" },
  { label: "Refugee or Asylum-Seeker Status", value: "refugee-asylum-status" },
  { label: "No Recourse to Public Funds (NRPF)", value: "nrpf" },
  { label: "Health or Disability Challenges", value: "health-disability" },
  { label: "Unplanned Life Events", value: "unplanned-events" },
  { label: "Homeless", value: "homeless" },
  { label: "At Risk of Homelessness", value: "at-risk-homeless" },
  { label: "Domestic Violence", value: "domestic-violence" },
  { label: "Mental Health", value: "mental-health" },
  { label: "Substance Misuse", value: "substance-misuse" },
  { label: "Ex-Offender", value: "ex-offender" },
] as const;

export const IdentificationTypeOptions = [
  { label: "Passport (UK or International)", value: "passport" },
  {
    label: "UK Driving Licence (Full or Provisional)",
    value: "driving-licence",
  },
  { label: "Biometric Residence Permit (BRP)", value: "brp" },
  { label: "EU/EEA National ID Card", value: "eu-id-card" },
  { label: "Police Registration Certificate", value: "police-certificate" },
  { label: "Birth Certificate", value: "birth-certificate" },
  {
    label: "Marriage or Civil Partnership Certificate",
    value: "marriage-certificate",
  },
  { label: "HMRC Tax Notification", value: "hmrc-notification" },
  {
    label: "DWP Letter (e.g., Universal Credit, Pension Credit, or ESA)",
    value: "dwp-letter",
  },
  {
    label: "Immigration Status Document (issued by the Home Office)",
    value: "immigration-document",
  },
  {
    label: "Utility Bill (dated within the last 3 months)",
    value: "utility-bill",
  },
  {
    label: "Bank Statement (dated within the last 3 months)",
    value: "bank-statement",
  },
  {
    label:
      "Letter from Local Authority or Social Services (confirming identity and address)",
    value: "authority-letter",
  },
] as const;

export const CountryOptions = [
  { label: "United Kingdom", value: "united-kingdom" },
  { label: "United States", value: "united-states" },
  { label: "Canada", value: "canada" },
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Albania", value: "albania" },
  { label: "Algeria", value: "algeria" },
  { label: "American Samoa", value: "american-samoa" },
  { label: "Andorra", value: "andorra" },
  { label: "Angola", value: "angola" },
  { label: "Anguilla", value: "anguilla" },
  { label: "Antarctica", value: "antarctica" },
  { label: "Antigua and Barbuda", value: "antigua-and-barbuda" },
  { label: "Argentina", value: "argentina" },
  { label: "Armenia", value: "armenia" },
  { label: "Aruba", value: "aruba" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas (the)", value: "bahamas-the" },
  { label: "Bahrain", value: "bahrain" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  { label: "Belarus", value: "belarus" },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  { label: "Benin", value: "benin" },
  { label: "Bermuda", value: "bermuda" },
  { label: "Bhutan", value: "bhutan" },
  {
    label: "Bolivia (Plurinational State of)",
    value: "bolivia-plurinational-state-of",
  },
  {
    label: "Bonaire, Sint Eustatius and Saba",
    value: "bonaire-sint-eustatius-and-saba",
  },
  { label: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
  { label: "Botswana", value: "botswana" },
  { label: "Bouvet Island", value: "bouvet-island" },
  { label: "Brazil", value: "brazil" },
  {
    label: "British Indian Ocean Territory (the)",
    value: "british-indian-ocean-territory-the",
  },
  { label: "Brunei Darussalam", value: "brunei-darussalam" },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkina-faso" },
  { label: "Burundi", value: "burundi" },
  { label: "Cabo Verde", value: "cabo-verde" },
  { label: "Cambodia", value: "cambodia" },
  { label: "Cameroon", value: "cameroon" },
  { label: "Cayman Islands (the)", value: "cayman-islands-the" },
  {
    label: "Central African Republic (the)",
    value: "central-african-republic-the",
  },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  { label: "China", value: "china" },
  { label: "Christmas Island", value: "christmas-island" },
  {
    label: "Cocos (Keeling) Islands (the)",
    value: "cocos-keeling-islands-the",
  },
  { label: "Colombia", value: "colombia" },
  { label: "Comoros (the)", value: "comoros-the" },
  {
    label: "Congo (the Democratic Republic of the)",
    value: "congo-the-democratic-republic-of-the",
  },
  { label: "Congo (the)", value: "congo-the" },
  { label: "Cook Islands (the)", value: "cook-islands-the" },
  { label: "Costa Rica", value: "costa-rica" },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  { label: "Curaçao", value: "curacao" },
  { label: "Cyprus", value: "cyprus" },
  { label: "Czechia", value: "czechia" },
  { label: "Côte d'Ivoire", value: "cote-divoire" },
  { label: "Denmark", value: "denmark" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominica", value: "dominica" },
  { label: "Dominican Republic (the)", value: "dominican-republic-the" },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  { label: "El Salvador", value: "el-salvador" },
  { label: "Equatorial Guinea", value: "equatorial-guinea" },
  { label: "Eritrea", value: "eritrea" },
  { label: "Estonia", value: "estonia" },
  { label: "Eswatini", value: "eswatini" },
  { label: "Ethiopia", value: "ethiopia" },
  {
    label: "Falkland Islands (the) [Malvinas]",
    value: "falkland-islands-the-malvinas",
  },
  { label: "Faroe Islands (the)", value: "faroe-islands-the" },
  { label: "Fiji", value: "fiji" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "French Guiana", value: "french-guiana" },
  { label: "French Polynesia", value: "french-polynesia" },
  {
    label: "French Southern Territories (the)",
    value: "french-southern-territories-the",
  },
  { label: "Gabon", value: "gabon" },
  { label: "Gambia (the)", value: "gambia-the" },
  { label: "Georgia", value: "georgia" },
  { label: "Germany", value: "germany" },
  { label: "Ghana", value: "ghana" },
  { label: "Gibraltar", value: "gibraltar" },
  { label: "Greece", value: "greece" },
  { label: "Greenland", value: "greenland" },
  { label: "Grenada", value: "grenada" },
  { label: "Guadeloupe", value: "guadeloupe" },
  { label: "Guam", value: "guam" },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guernsey", value: "guernsey" },
  { label: "Guinea", value: "guinea" },
  { label: "Guinea-Bissau", value: "guinea-bissau" },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  {
    label: "Heard Island and McDonald Islands",
    value: "heard-island-and-mcdonald-islands",
  },
  { label: "Holy See (the)", value: "holy-see-the" },
  { label: "Honduras", value: "honduras" },
  { label: "Hong Kong", value: "hong-kong" },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran (Islamic Republic of)", value: "iran-islamic-republic-of" },
  { label: "Iraq", value: "iraq" },
  { label: "Ireland", value: "ireland" },
  { label: "Isle of Man", value: "isle-of-man" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  { label: "Jersey", value: "jersey" },
  { label: "Jordan", value: "jordan" },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  { label: "Kiribati", value: "kiribati" },
  {
    label: "Korea (the Democratic People's Republic of)",
    value: "korea-the-democratic-peoples-republic-of",
  },
  { label: "Korea (the Republic of)", value: "korea-the-republic-of" },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  {
    label: "Lao People's Democratic Republic (the)",
    value: "lao-peoples-democratic-republic-the",
  },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  { label: "Lesotho", value: "lesotho" },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  { label: "Macao", value: "macao" },
  { label: "Madagascar", value: "madagascar" },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Maldives", value: "maldives" },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  { label: "Marshall Islands (the)", value: "marshall-islands-the" },
  { label: "Martinique", value: "martinique" },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  { label: "Mayotte", value: "mayotte" },
  { label: "Mexico", value: "mexico" },
  {
    label: "Micronesia (Federated States of)",
    value: "micronesia-federated-states-of",
  },
  { label: "Moldova (the Republic of)", value: "moldova-the-republic-of" },
  { label: "Monaco", value: "monaco" },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  { label: "Montserrat", value: "montserrat" },
  { label: "Morocco", value: "morocco" },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar", value: "myanmar" },
  { label: "Namibia", value: "namibia" },
  { label: "Nauru", value: "nauru" },
  { label: "Nepal", value: "nepal" },
  { label: "Netherlands (the)", value: "netherlands-the" },
  { label: "New Caledonia", value: "new-caledonia" },
  { label: "New Zealand", value: "new-zealand" },
  { label: "Nicaragua", value: "nicaragua" },
  { label: "Niger (the)", value: "niger-the" },
  { label: "Nigeria", value: "nigeria" },
  { label: "Niue", value: "niue" },
  { label: "Norfolk Island", value: "norfolk-island" },
  {
    label: "Northern Mariana Islands (the)",
    value: "northern-mariana-islands-the",
  },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Palau", value: "palau" },
  { label: "Palestine, State of", value: "palestine-state-of" },
  { label: "Panama", value: "panama" },
  { label: "Papua New Guinea", value: "papua-new-guinea" },
  { label: "Paraguay", value: "paraguay" },
  { label: "Peru", value: "peru" },
  { label: "Philippines (the)", value: "philippines-the" },
  { label: "Pitcairn", value: "pitcairn" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Puerto Rico", value: "puerto-rico" },
  { label: "Qatar", value: "qatar" },
  {
    label: "Republic of North Macedonia",
    value: "republic-of-north-macedonia",
  },
  { label: "Romania", value: "romania" },
  { label: "Russian Federation (the)", value: "russian-federation-the" },
  { label: "Rwanda", value: "rwanda" },
  { label: "Réunion", value: "reunion" },
  { label: "Saint Barthélemy", value: "saint-barthelemy" },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    value: "saint-helena-ascension-and-tristan-da-cunha",
  },
  { label: "Saint Kitts and Nevis", value: "saint-kitts-and-nevis" },
  { label: "Saint Lucia", value: "saint-lucia" },
  { label: "Saint Martin (French part)", value: "saint-martin-french-part" },
  { label: "Saint Pierre and Miquelon", value: "saint-pierre-and-miquelon" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint-vincent-and-the-grenadines",
  },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "san-marino" },
  { label: "Sao Tome and Principe", value: "sao-tome-and-principe" },
  { label: "Saudi Arabia", value: "saudi-arabia" },
  { label: "Senegal", value: "senegal" },
  { label: "Serbia", value: "serbia" },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierra-leone" },
  { label: "Singapore", value: "singapore" },
  { label: "Sint Maarten (Dutch part)", value: "sint-maarten-dutch-part" },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  { label: "Solomon Islands", value: "solomon-islands" },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "south-africa" },
  {
    label: "South Georgia and the South Sandwich Islands",
    value: "south-georgia-and-the-south-sandwich-islands",
  },
  { label: "South Sudan", value: "south-sudan" },
  { label: "Spain", value: "spain" },
  { label: "Sri Lanka", value: "sri-lanka" },
  { label: "Sudan (the)", value: "sudan-the" },
  { label: "Suriname", value: "suriname" },
  { label: "Svalbard and Jan Mayen", value: "svalbard-and-jan-mayen" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syrian Arab Republic", value: "syrian-arab-republic" },
  { label: "Taiwan", value: "taiwan" },
  { label: "Tajikistan", value: "tajikistan" },
  {
    label: "Tanzania, United Republic of",
    value: "tanzania-united-republic-of",
  },
  { label: "Thailand", value: "thailand" },
  { label: "Timor-Leste", value: "timor-leste" },
  { label: "Togo", value: "togo" },
  { label: "Tokelau", value: "tokelau" },
  { label: "Tonga", value: "tonga" },
  { label: "Trinidad and Tobago", value: "trinidad-and-tobago" },
  { label: "Tunisia", value: "tunisia" },
  { label: "Turkey", value: "turkey" },
  { label: "Turkmenistan", value: "turkmenistan" },
  {
    label: "Turks and Caicos Islands (the)",
    value: "turks-and-caicos-islands-the",
  },
  { label: "Tuvalu", value: "tuvalu" },
  { label: "Uganda", value: "uganda" },
  { label: "Ukraine", value: "ukraine" },
  { label: "United Arab Emirates (the)", value: "united-arab-emirates-the" },
  {
    label: "United Kingdom of Great Britain and Northern Ireland (the)",
    value: "united-kingdom-of-great-britain-and-northern-ireland-the",
  },
  {
    label: "United States Minor Outlying Islands (the)",
    value: "united-states-minor-outlying-islands-the",
  },
  {
    label: "United States of America (the)",
    value: "united-states-of-america-the",
  },
  { label: "Uruguay", value: "uruguay" },
  { label: "Uzbekistan", value: "uzbekistan" },
  { label: "Vanuatu", value: "vanuatu" },
  {
    label: "Venezuela (Bolivarian Republic of)",
    value: "venezuela-bolivarian-republic-of",
  },
  { label: "Viet Nam", value: "viet-nam" },
  { label: "Virgin Islands (British)", value: "virgin-islands-british" },
  { label: "Virgin Islands (U.S.)", value: "virgin-islands-us" },
  { label: "Wallis and Futuna", value: "wallis-and-futuna" },
  { label: "Western Sahara", value: "western-sahara" },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
  { label: "Åland Islands", value: "aland-islands" },
] as const;

export const NationalityOptions = [
  { label: "Afghan", value: "afghan" },
  { label: "Albanian", value: "albanian" },
  { label: "Algerian", value: "algerian" },
  { label: "American", value: "american" },
  { label: "Andorran", value: "andorran" },
  { label: "Angolan", value: "angolan" },
  { label: "Antiguans", value: "antiguans" },
  { label: "Argentinean", value: "argentinean" },
  { label: "Armenian", value: "armenian" },
  { label: "Australian", value: "australian" },
  { label: "Austrian", value: "austrian" },
  { label: "Azerbaijani", value: "azerbaijani" },
  { label: "Bahamian", value: "bahamian" },
  { label: "Bahraini", value: "bahraini" },
  { label: "Bangladeshi", value: "bangladeshi" },
  { label: "Barbadian", value: "barbadian" },
  { label: "Barbudans", value: "barbudans" },
  { label: "Batswana", value: "batswana" },
  { label: "Belarusian", value: "belarusian" },
  { label: "Belgian", value: "belgian" },
  { label: "Belizean", value: "belizean" },
  { label: "Beninese", value: "beninese" },
  { label: "Bhutanese", value: "bhutanese" },
  { label: "Bolivian", value: "bolivian" },
  { label: "Bosnian", value: "bosnian" },
  { label: "Brazilian", value: "brazilian" },
  { label: "British", value: "british" },
  { label: "Bruneian", value: "bruneian" },
  { label: "Bulgarian", value: "bulgarian" },
  { label: "Burkinabe", value: "burkinabe" },
  { label: "Burmese", value: "burmese" },
  { label: "Burundian", value: "burundian" },
  { label: "Cambodian", value: "cambodian" },
  { label: "Cameroonian", value: "cameroonian" },
  { label: "Canadian", value: "canadian" },
  { label: "Cape Verdean", value: "cape-verdean" },
  { label: "Central African", value: "central-african" },
  { label: "Chadian", value: "chadian" },
  { label: "Chilean", value: "chilean" },
  { label: "Chinese", value: "chinese" },
  { label: "Colombian", value: "colombian" },
  { label: "Comoran", value: "comoran" },
  { label: "Congolese", value: "congolese" },
  { label: "Costa Rican", value: "costa-rican" },
  { label: "Croatian", value: "croatian" },
  { label: "Cuban", value: "cuban" },
  { label: "Cypriot", value: "cypriot" },
  { label: "Czech", value: "czech" },
  { label: "Danish", value: "danish" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominican", value: "dominican" },
  { label: "Dutch", value: "dutch" },
  { label: "East Timorese", value: "east-timorese" },
  { label: "Ecuadorean", value: "ecuadorean" },
  { label: "Egyptian", value: "egyptian" },
  { label: "Emirian", value: "emirian" },
  { label: "Equatorial Guinean", value: "equatorial-guinean" },
  { label: "Eritrean", value: "eritrean" },
  { label: "Estonian", value: "estonian" },
  { label: "Ethiopian", value: "ethiopian" },
  { label: "Fijian", value: "fijian" },
  { label: "Filipino", value: "filipino" },
  { label: "Finnish", value: "finnish" },
  { label: "French", value: "french" },
  { label: "Gabonese", value: "gabonese" },
  { label: "Gambian", value: "gambian" },
  { label: "Georgian", value: "georgian" },
  { label: "German", value: "german" },
  { label: "Ghanaian", value: "ghanaian" },
  { label: "Greek", value: "greek" },
  { label: "Grenadian", value: "grenadian" },
  { label: "Guatemalan", value: "guatemalan" },
  { label: "Guinea-Bissauan", value: "guinea-bissauan" },
  { label: "Guinean", value: "guinean" },
  { label: "Guyanese", value: "guyanese" },
  { label: "Haitian", value: "haitian" },
  { label: "Herzegovinian", value: "herzegovinian" },
  { label: "Honduran", value: "honduran" },
  { label: "Hungarian", value: "hungarian" },
  { label: "I-Kiribati", value: "i-kiribati" },
  { label: "Icelander", value: "icelander" },
  { label: "Indian", value: "indian" },
  { label: "Indonesian", value: "indonesian" },
  { label: "Iranian", value: "iranian" },
  { label: "Iraqi", value: "iraqi" },
  { label: "Irish", value: "irish" },
  { label: "Israeli", value: "israeli" },
  { label: "Italian", value: "italian" },
  { label: "Ivorian", value: "ivorian" },
  { label: "Jamaican", value: "jamaican" },
  { label: "Japanese", value: "japanese" },
  { label: "Jordanian", value: "jordanian" },
  { label: "Kazakhstani", value: "kazakhstani" },
  { label: "Kenyan", value: "kenyan" },
  { label: "Kittian and Nevisian", value: "kittian-and-nevisian" },
  { label: "Kuwaiti", value: "kuwaiti" },
  { label: "Kyrgyz", value: "kyrgyz" },
  { label: "Laotian", value: "laotian" },
  { label: "Latvian", value: "latvian" },
  { label: "Lebanese", value: "lebanese" },
  { label: "Liberian", value: "liberian" },
  { label: "Libyan", value: "libyan" },
  { label: "Liechtensteiner", value: "liechtensteiner" },
  { label: "Lithuanian", value: "lithuanian" },
  { label: "Luxembourger", value: "luxembourger" },
  { label: "Macedonian", value: "macedonian" },
  { label: "Malagasy", value: "malagasy" },
  { label: "Malawian", value: "malawian" },
  { label: "Malaysian", value: "malaysian" },
  { label: "Maldivan", value: "maldivan" },
  { label: "Malian", value: "malian" },
  { label: "Maltese", value: "maltese" },
  { label: "Marshallese", value: "marshallese" },
  { label: "Mauritanian", value: "mauritanian" },
  { label: "Mauritian", value: "mauritian" },
  { label: "Mexican", value: "mexican" },
  { label: "Micronesian", value: "micronesian" },
  { label: "Moldovan", value: "moldovan" },
  { label: "Monacan", value: "monacan" },
  { label: "Mongolian", value: "mongolian" },
  { label: "Moroccan", value: "moroccan" },
  { label: "Mosotho", value: "mosotho" },
  { label: "Motswana", value: "motswana" },
  { label: "Mozambican", value: "mozambican" },
  { label: "Namibian", value: "namibian" },
  { label: "Nauruan", value: "nauruan" },
  { label: "Nepali", value: "nepali" },
  { label: "New Zealander", value: "new-zealander" },
  { label: "Nicaraguan", value: "nicaraguan" },
  { label: "Nigerian", value: "nigerian" },
  { label: "Nigerien", value: "nigerien" },
  { label: "North Korean", value: "north-korean" },
  { label: "Northern Irish", value: "northern-irish" },
  { label: "Norwegian", value: "norwegian" },
  { label: "Omani", value: "omani" },
  { label: "Pakistani", value: "pakistani" },
  { label: "Palauan", value: "palauan" },
  { label: "Panamanian", value: "panamanian" },
  { label: "Papua New Guinean", value: "papua-new-guinean" },
  { label: "Paraguayan", value: "paraguayan" },
  { label: "Peruvian", value: "peruvian" },
  { label: "Polish", value: "polish" },
  { label: "Portuguese", value: "portuguese" },
  { label: "Qatari", value: "qatari" },
  { label: "Romanian", value: "romanian" },
  { label: "Russian", value: "russian" },
  { label: "Rwandan", value: "rwandan" },
  { label: "Saint Lucian", value: "saint-lucian" },
  { label: "Salvadoran", value: "salvadoran" },
  { label: "Samoan", value: "samoan" },
  { label: "San Marinese", value: "san-marinese" },
  { label: "Sao Tomean", value: "sao-tomean" },
  { label: "Saudi", value: "saudi" },
  { label: "Scottish", value: "scottish" },
  { label: "Senegalese", value: "senegalese" },
  { label: "Serbian", value: "serbian" },
  { label: "Seychellois", value: "seychellois" },
  { label: "Sierra Leonean", value: "sierra-leonean" },
  { label: "Singaporean", value: "singaporean" },
  { label: "Slovakian", value: "slovakian" },
  { label: "Slovenian", value: "slovenian" },
  { label: "Solomon Islander", value: "solomon-islander" },
  { label: "Somali", value: "somali" },
  { label: "South African", value: "south-african" },
  { label: "South Korean", value: "south-korean" },
  { label: "Spanish", value: "spanish" },
  { label: "Sri Lankan", value: "sri-lankan" },
  { label: "Sudanese", value: "sudanese" },
  { label: "Surinamer", value: "surinamer" },
  { label: "Swazi", value: "swazi" },
  { label: "Swedish", value: "swedish" },
  { label: "Swiss", value: "swiss" },
  { label: "Syrian", value: "syrian" },
  { label: "Taiwanese", value: "taiwanese" },
  { label: "Tajik", value: "tajik" },
  { label: "Tanzanian", value: "tanzanian" },
  { label: "Thai", value: "thai" },
  { label: "Togolese", value: "togolese" },
  { label: "Tongan", value: "tongan" },
  { label: "Trinidadian/Tobagonian", value: "trinidadian-tobagonian" },
  { label: "Tunisian", value: "tunisian" },
  { label: "Turkish", value: "turkish" },
  { label: "Tuvaluan", value: "tuvaluan" },
  { label: "Ugandan", value: "ugandan" },
  { label: "Ukrainian", value: "ukrainian" },
  { label: "Uruguayan", value: "uruguayan" },
  { label: "Uzbekistani", value: "uzbekistani" },
  { label: "Venezuelan", value: "venezuelan" },
  { label: "Vietnamese", value: "vietnamese" },
  { label: "Welsh", value: "welsh" },
  { label: "Yemenite", value: "yemenite" },
  { label: "Zambian", value: "zambian" },
  { label: "Zimbabwean", value: "zimbabwean" },
] as const;
